version: '2'
services:
  jhipstersampleapplication190720-app:
    image: jhipstersampleapplication190720
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipstersampleapplication190720-postgresql:5432/jhipsterSampleApplication190720
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jhipstersampleapplication190720-postgresql:
    extends:
      file: postgresql.yml
      service: jhipstersampleapplication190720-postgresql
