version: '2'
services:
  jhipstersampleapplication190720-postgresql:
    image: postgres:11.3
    # volumes:
    #     - ~/volumes/jhipster/jhipsterSampleApplication190720/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jhipsterSampleApplication190720
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
